// GENERATED by scripts/gen-art-registry.mjs — do not edit by hand; edit art/manifest.json + regenerate.
/**
 * Generated-art registry: the only place that knows asset paths and frame
 * geometry. Every sheet under `public/assets/generated/` was produced by the
 * `game-art` skill (native generate_image + sprite-forge export) against
 * `art/style.json`, so the whole set shares one style contract.
 *
 * Frame geometry and per-action scale come from each asset's
 * `sprite-metadata.json` and `art/manifest.json` — never hand-guessed. To
 * change a row here, edit the manifest (or re-export the asset) and re-run
 * `node scripts/gen-art-registry.mjs`.
 *
 * Pure data, no Phaser import.
 */

/**
 * How a slice's tuning points a gameplay role at loaded art: `{ key }` for a
 * single-image texture, `{ key, frame }` for one cell of a sheet (the shape
 * `ICON` entries already have). One declaration for every slice — a slot is
 * addressing art, which is what this registry is for.
 *
 * Resolve it once, at construction: when
 * `scene.textures.exists(slot.key)` is false the slice draws its procedural
 * fallback instead, so a pruned art group degrades instead of rendering
 * missing-texture boxes. Tint belongs to that fallback only — generated art
 * carries its own colour.
 */
export interface ArtSlot {
  /** Texture key from `TEXTURE`/`ANIM`/`ICON` (or a raw registry `key`). */
  key: string;
  /** Frame on a multi-frame sheet: index, or an atlas frame name. */
  frame?: string | number;
}

export interface SpriteAsset {
  /** Phaser texture key; also the animation key when `frames > 1`. */
  key: string;
  /**
   * `art/manifest.json` group this asset belongs to. `PreloadScene` loads a
   * row only when its group is listed in the active slice's `ART_GROUPS`, so a
   * game downloads the art its gameplay actually uses and nothing else.
   */
  group: string;
  /** Path under `public/`. */
  path: string;
  frameWidth: number;
  frameHeight: number;
  frames: number;
  /** ms per frame; ignored when `frames === 1`. */
  duration: number;
  loop: boolean;
  /**
   * Display-size compensation. Generated actions do not fill their cell to the
   * same height, so switching animation would visibly resize the character.
   * The entity multiplies its tuned size by this factor, which is
   * `baseActionHeight / thisActionHeight` (see `baseAction` in
   * art/manifest.json). Default 1.
   */
  scale?: number;
  /**
   * Which way the unflipped art faces. Some art reads as moving LEFT (cloak
   * trails right), so flipping on `velocity.x < 0` would face it backwards.
   * Default true.
   */
  facesRight?: boolean;
}

/** Animated sheets: loaded as spritesheets, one animation created per entry. */
export const SPRITES: readonly SpriteAsset[] = [
  // Hero
  { key: 'hero-idle', group: 'hero', path: 'assets/generated/hero/hero-idle/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 150, loop: true },
  { key: 'hero-run', group: 'hero', path: 'assets/generated/hero/hero-run/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 6, duration: 110, loop: true, scale: 1.121 },
  { key: 'hero-hurt', group: 'hero', path: 'assets/generated/hero/hero-hurt/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 2, duration: 90, loop: false, scale: 1.109 },
  { key: 'hero-channel', group: 'hero', path: 'assets/generated/hero/hero-channel/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 140, loop: true, scale: 0.937 },
  { key: 'hero-death', group: 'hero', path: 'assets/generated/hero/hero-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 6, duration: 100, loop: false, scale: 1.15 },
  { key: 'hero-extract', group: 'hero', path: 'assets/generated/hero/hero-extract/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 6, duration: 110, loop: false, scale: 1.154 },

  // Enemies Light
  { key: 'enemy-husk-move', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-husk-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 140, loop: true },
  { key: 'enemy-husk-death', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-husk-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-wretch-move', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-wretch-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: true },
  { key: 'enemy-wretch-death', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-wretch-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-ratking-move', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-ratking-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'enemy-ratking-death', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-ratking-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false },
  { key: 'enemy-bonecaster-move', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-bonecaster-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 150, loop: true },
  { key: 'enemy-bonecaster-attack', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-bonecaster-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false },
  { key: 'enemy-bonecaster-death', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-bonecaster-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-thornhound-move', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-thornhound-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: true },
  { key: 'enemy-thornhound-attack', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-thornhound-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false },
  { key: 'enemy-thornhound-death', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-thornhound-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-shroudmoth-move', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-shroudmoth-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 130, loop: true },
  { key: 'enemy-shroudmoth-death', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-shroudmoth-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false },
  { key: 'enemy-pyreling-move', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-pyreling-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'enemy-pyreling-death', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-pyreling-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'enemy-ashwraith-move', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-ashwraith-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 130, loop: true },
  { key: 'enemy-ashwraith-death', group: 'enemies-light', path: 'assets/generated/enemies-light/enemy-ashwraith-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false },

  // Enemies Heavy
  { key: 'enemy-paleknight-move', group: 'enemies-heavy', path: 'assets/generated/enemies-heavy/enemy-paleknight-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 160, loop: true },
  { key: 'enemy-paleknight-death', group: 'enemies-heavy', path: 'assets/generated/enemies-heavy/enemy-paleknight-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false },
  { key: 'enemy-marrowworm-move', group: 'enemies-heavy', path: 'assets/generated/enemies-heavy/enemy-marrowworm-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 140, loop: true },
  { key: 'enemy-marrowworm-death', group: 'enemies-heavy', path: 'assets/generated/enemies-heavy/enemy-marrowworm-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-dirgebell-move', group: 'enemies-heavy', path: 'assets/generated/enemies-heavy/enemy-dirgebell-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 150, loop: true },
  { key: 'enemy-dirgebell-death', group: 'enemies-heavy', path: 'assets/generated/enemies-heavy/enemy-dirgebell-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-gildedghoul-move', group: 'enemies-heavy', path: 'assets/generated/enemies-heavy/enemy-gildedghoul-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: true },
  { key: 'enemy-gildedghoul-death', group: 'enemies-heavy', path: 'assets/generated/enemies-heavy/enemy-gildedghoul-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },

  // Elites Warden
  { key: 'elite-reaper-move', group: 'elites-warden', path: 'assets/generated/elites-warden/elite-reaper-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 140, loop: true, scale: 0.909 },
  { key: 'elite-reaper-attack', group: 'elites-warden', path: 'assets/generated/elites-warden/elite-reaper-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false, scale: 0.928 },
  { key: 'elite-reaper-death', group: 'elites-warden', path: 'assets/generated/elites-warden/elite-reaper-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false, scale: 1.172 },
  { key: 'elite-matron-move', group: 'elites-warden', path: 'assets/generated/elites-warden/elite-matron-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 150, loop: true, scale: 1.793 },
  { key: 'elite-matron-attack', group: 'elites-warden', path: 'assets/generated/elites-warden/elite-matron-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false, scale: 2.308 },
  { key: 'elite-matron-death', group: 'elites-warden', path: 'assets/generated/elites-warden/elite-matron-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false, scale: 1.864 },
  { key: 'elite-herald-move', group: 'elites-warden', path: 'assets/generated/elites-warden/elite-herald-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 140, loop: true, scale: 1.002 },
  { key: 'elite-herald-attack', group: 'elites-warden', path: 'assets/generated/elites-warden/elite-herald-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false, scale: 1.009 },
  { key: 'elite-herald-death', group: 'elites-warden', path: 'assets/generated/elites-warden/elite-herald-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false, scale: 1.187 },
  { key: 'boss-warden-idle', group: 'elites-warden', path: 'assets/generated/elites-warden/boss-warden-idle/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 160, loop: true },
  { key: 'boss-warden-sweep', group: 'elites-warden', path: 'assets/generated/elites-warden/boss-warden-sweep/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 6, duration: 100, loop: false, scale: 1.216 },
  { key: 'boss-warden-summon', group: 'elites-warden', path: 'assets/generated/elites-warden/boss-warden-summon/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 130, loop: false, scale: 1.009 },
  { key: 'boss-warden-enrage', group: 'elites-warden', path: 'assets/generated/elites-warden/boss-warden-enrage/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: true, scale: 0.975 },
  { key: 'boss-warden-death', group: 'elites-warden', path: 'assets/generated/elites-warden/boss-warden-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 8, duration: 110, loop: false, scale: 1.568 },
  { key: 'boss-warden-idle-outlands', group: 'elites-warden', path: 'assets/generated/elites-warden/boss-warden-idle-outlands/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 160, loop: true, scale: 0.997 },
  { key: 'boss-warden-idle-desert', group: 'elites-warden', path: 'assets/generated/elites-warden/boss-warden-idle-desert/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 160, loop: true, scale: 0.972 },
  { key: 'boss-warden-idle-winter', group: 'elites-warden', path: 'assets/generated/elites-warden/boss-warden-idle-winter/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 160, loop: true, scale: 0.985 },

  // Pickups Fx
  { key: 'shard-glint', group: 'pickups-fx', path: 'assets/generated/pickups-fx/shard-glint/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 90, loop: true },
  { key: 'xp-mote', group: 'pickups-fx', path: 'assets/generated/pickups-fx/xp-mote/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 100, loop: true },
  { key: 'relic-hover-t1', group: 'pickups-fx', path: 'assets/generated/pickups-fx/relic-hover-t1/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 140, loop: true },
  { key: 'relic-hover-t2', group: 'pickups-fx', path: 'assets/generated/pickups-fx/relic-hover-t2/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 140, loop: true },
  { key: 'relic-hover-t3', group: 'pickups-fx', path: 'assets/generated/pickups-fx/relic-hover-t3/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 140, loop: true },
  { key: 'relic-hover-t4', group: 'pickups-fx', path: 'assets/generated/pickups-fx/relic-hover-t4/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 140, loop: true },
  { key: 'chest-open', group: 'pickups-fx', path: 'assets/generated/pickups-fx/chest-open/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 110, loop: false },
  { key: 'casket-sparkle', group: 'pickups-fx', path: 'assets/generated/pickups-fx/casket-sparkle/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 2, duration: 160, loop: true },

  // Gates Collapse
  { key: 'gate-opening', group: 'gates-collapse', path: 'assets/generated/gates-collapse/gate-opening/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 6, duration: 110, loop: false },
  { key: 'gate-open', group: 'gates-collapse', path: 'assets/generated/gates-collapse/gate-open/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 130, loop: true },
  { key: 'gate-closing', group: 'gates-collapse', path: 'assets/generated/gates-collapse/gate-closing/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 110, loop: true },
  { key: 'collapse-ring', group: 'gates-collapse', path: 'assets/generated/gates-collapse/collapse-ring/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 90, loop: true },

  // Zone Castle
  { key: 'enemy-chapelghast-move', group: 'zone-castle', path: 'assets/generated/zone-castle/enemy-chapelghast-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'enemy-chapelghast-death', group: 'zone-castle', path: 'assets/generated/zone-castle/enemy-chapelghast-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-gargoyle-move', group: 'zone-castle', path: 'assets/generated/zone-castle/enemy-gargoyle-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 150, loop: true },
  { key: 'enemy-gargoyle-attack', group: 'zone-castle', path: 'assets/generated/zone-castle/enemy-gargoyle-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false },
  { key: 'enemy-gargoyle-death', group: 'zone-castle', path: 'assets/generated/zone-castle/enemy-gargoyle-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false },
  { key: 'props-castle-a', group: 'zone-castle', path: 'assets/generated/zone-castle/props-castle-a/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 120, loop: true },
  { key: 'props-castle-b', group: 'zone-castle', path: 'assets/generated/zone-castle/props-castle-b/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 120, loop: true },

  // Zone Outlands
  { key: 'enemy-kite-move', group: 'zone-outlands', path: 'assets/generated/zone-outlands/enemy-kite-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: true },
  { key: 'enemy-kite-death', group: 'zone-outlands', path: 'assets/generated/zone-outlands/enemy-kite-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false },
  { key: 'enemy-giant-move', group: 'zone-outlands', path: 'assets/generated/zone-outlands/enemy-giant-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 170, loop: true },
  { key: 'enemy-giant-attack', group: 'zone-outlands', path: 'assets/generated/zone-outlands/enemy-giant-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false },
  { key: 'enemy-giant-death', group: 'zone-outlands', path: 'assets/generated/zone-outlands/enemy-giant-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: false },
  { key: 'props-outlands-a', group: 'zone-outlands', path: 'assets/generated/zone-outlands/props-outlands-a/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 120, loop: true },
  { key: 'props-outlands-b', group: 'zone-outlands', path: 'assets/generated/zone-outlands/props-outlands-b/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 120, loop: true },

  // Zone Desert
  { key: 'enemy-leech-move', group: 'zone-desert', path: 'assets/generated/zone-desert/enemy-leech-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 130, loop: true },
  { key: 'enemy-leech-attack', group: 'zone-desert', path: 'assets/generated/zone-desert/enemy-leech-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false },
  { key: 'enemy-leech-death', group: 'zone-desert', path: 'assets/generated/zone-desert/enemy-leech-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-scarab-move', group: 'zone-desert', path: 'assets/generated/zone-desert/enemy-scarab-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: true },
  { key: 'enemy-scarab-death', group: 'zone-desert', path: 'assets/generated/zone-desert/enemy-scarab-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false },
  { key: 'props-desert-a', group: 'zone-desert', path: 'assets/generated/zone-desert/props-desert-a/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 120, loop: true },
  { key: 'props-desert-b', group: 'zone-desert', path: 'assets/generated/zone-desert/props-desert-b/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 120, loop: true },

  // Zone Winter
  { key: 'enemy-widow-move', group: 'zone-winter', path: 'assets/generated/zone-winter/enemy-widow-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 140, loop: true },
  { key: 'enemy-widow-attack', group: 'zone-winter', path: 'assets/generated/zone-winter/enemy-widow-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-widow-death', group: 'zone-winter', path: 'assets/generated/zone-winter/enemy-widow-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-yeti-move', group: 'zone-winter', path: 'assets/generated/zone-winter/enemy-yeti-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 160, loop: true },
  { key: 'enemy-yeti-attack', group: 'zone-winter', path: 'assets/generated/zone-winter/enemy-yeti-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'enemy-yeti-death', group: 'zone-winter', path: 'assets/generated/zone-winter/enemy-yeti-death/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: false },
  { key: 'props-winter-a', group: 'zone-winter', path: 'assets/generated/zone-winter/props-winter-a/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 120, loop: true },
  { key: 'props-winter-b', group: 'zone-winter', path: 'assets/generated/zone-winter/props-winter-b/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 120, loop: true },

  // Ui Icons
  { key: 'icons', group: 'ui-icons', path: 'assets/generated/ui-icons/icons/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 16, duration: 120, loop: true },
] as const;

/** Single-image textures: no animation, no frame slicing. */
export const IMAGES: readonly SpriteAsset[] = [
  // Pickups Fx
  { key: 'bolt-arcane', group: 'pickups-fx', path: 'assets/generated/pickups-fx/bolt-arcane/sprite.png', frameWidth: 128, frameHeight: 128, frames: 1, duration: 0, loop: false },

  // Gates Collapse
  { key: 'gate-closed', group: 'gates-collapse', path: 'assets/generated/gates-collapse/gate-closed/sprite.png', frameWidth: 128, frameHeight: 128, frames: 1, duration: 0, loop: false },

  // Zone Castle
  { key: 'floor-castle', group: 'zone-castle', path: 'assets/generated/zone-castle/floor-castle/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'border-castle', group: 'zone-castle', path: 'assets/generated/zone-castle/border-castle/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },

  // Zone Outlands
  { key: 'floor-outlands', group: 'zone-outlands', path: 'assets/generated/zone-outlands/floor-outlands/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'border-outlands', group: 'zone-outlands', path: 'assets/generated/zone-outlands/border-outlands/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },

  // Zone Desert
  { key: 'floor-desert', group: 'zone-desert', path: 'assets/generated/zone-desert/floor-desert/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'border-desert', group: 'zone-desert', path: 'assets/generated/zone-desert/border-desert/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },

  // Zone Winter
  { key: 'floor-winter', group: 'zone-winter', path: 'assets/generated/zone-winter/floor-winter/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'border-winter', group: 'zone-winter', path: 'assets/generated/zone-winter/border-winter/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },

  // Ui Icons
  { key: 'emblem', group: 'ui-icons', path: 'assets/generated/ui-icons/emblem/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bg-menu', group: 'ui-icons', path: 'assets/generated/ui-icons/bg-menu/sprite.png', frameWidth: 1080, frameHeight: 1920, frames: 1, duration: 0, loop: false },
] as const;

const BY_KEY: Record<string, SpriteAsset> = {};
for (const asset of SPRITES) BY_KEY[asset.key] = asset;

/** Display-size factor for an animation key (1 when the asset needs none). */
export function artScale(key: string): number {
  return BY_KEY[key]?.scale ?? 1;
}

/** True when the unflipped art faces right. */
export function artFacesRight(key: string): boolean {
  return BY_KEY[key]?.facesRight ?? true;
}

/** Static texture keys, so gameplay code never types a string literal. */
export const TEXTURE = {
  shard: 'shard-glint',
  bullet: 'bolt-arcane',
  relicT1: 'relic-hover-t1',
  relicT2: 'relic-hover-t2',
  relicT3: 'relic-hover-t3',
  relicT4: 'relic-hover-t4',
  chest: 'chest-open',
  casket: 'casket-sparkle',
  gateClosed: 'gate-closed',
  floorCastle: 'floor-castle',
  borderCastle: 'border-castle',
  floorOutlands: 'floor-outlands',
  borderOutlands: 'border-outlands',
  floorDesert: 'floor-desert',
  borderDesert: 'border-desert',
  floorWinter: 'floor-winter',
  borderWinter: 'border-winter',
  logo: 'emblem',
  bgMenu: 'bg-menu',
} as const;

/** Frame index per icon inside the icon sheets. */
export const ICON = {
  'brazier-lit': { key: 'props-castle-a', frame: 0 },
  'brazier-cold': { key: 'props-castle-a', frame: 1 },
  banner: { key: 'props-castle-a', frame: 2 },
  coffin: { key: 'props-castle-a', frame: 3 },
  pew: { key: 'props-castle-a', frame: 4 },
  rubble: { key: 'props-castle-a', frame: 5 },
  torch: { key: 'props-castle-a', frame: 6 },
  statue: { key: 'props-castle-a', frame: 7 },
  bones: { key: 'props-castle-a', frame: 8 },
  font: { key: 'props-castle-b', frame: 0 },
  gatepiece: { key: 'props-castle-b', frame: 1 },
  candles: { key: 'props-castle-b', frame: 2 },
  tomb: { key: 'props-castle-b', frame: 3 },
  fence: { key: 'props-castle-b', frame: 4 },
  column: { key: 'props-castle-b', frame: 5 },
  shrine: { key: 'props-castle-b', frame: 6 },
  hook: { key: 'props-castle-b', frame: 7 },
  shield: { key: 'props-castle-b', frame: 8 },
  ribcage: { key: 'props-outlands-a', frame: 0 },
  gibbet: { key: 'props-outlands-a', frame: 1 },
  bramble: { key: 'props-outlands-a', frame: 2 },
  dune: { key: 'props-outlands-a', frame: 3 },
  cart: { key: 'props-outlands-a', frame: 4 },
  cairn: { key: 'props-outlands-a', frame: 5 },
  tree: { key: 'props-outlands-a', frame: 6 },
  mudpool: { key: 'props-outlands-a', frame: 7 },
  wheel: { key: 'props-outlands-a', frame: 8 },
  cage: { key: 'props-outlands-b', frame: 0 },
  scarecrow: { key: 'props-outlands-b', frame: 1 },
  vent: { key: 'props-outlands-b', frame: 2 },
  bonefence: { key: 'props-outlands-b', frame: 3 },
  milestone: { key: 'props-outlands-b', frame: 4 },
  perch: { key: 'props-outlands-b', frame: 5 },
  tent: { key: 'props-outlands-b', frame: 6 },
  firepit: { key: 'props-outlands-b', frame: 7 },
  'shrine-ash': { key: 'props-outlands-b', frame: 8 },
  statuehead: { key: 'props-desert-a', frame: 0 },
  well: { key: 'props-desert-a', frame: 1 },
  canopy: { key: 'props-desert-a', frame: 2 },
  ribs: { key: 'props-desert-a', frame: 3 },
  pit: { key: 'props-desert-a', frame: 4 },
  obelisk: { key: 'props-desert-a', frame: 5 },
  urns: { key: 'props-desert-a', frame: 6 },
  palm: { key: 'props-desert-a', frame: 7 },
  skulls: { key: 'props-desert-a', frame: 8 },
  wreck: { key: 'props-desert-b', frame: 0 },
  sunbanner: { key: 'props-desert-b', frame: 1 },
  mound: { key: 'props-desert-b', frame: 2 },
  cistern: { key: 'props-desert-b', frame: 3 },
  lintel: { key: 'props-desert-b', frame: 4 },
  salt: { key: 'props-desert-b', frame: 5 },
  vulture: { key: 'props-desert-b', frame: 6 },
  awning: { key: 'props-desert-b', frame: 7 },
  'shrine-sun': { key: 'props-desert-b', frame: 8 },
  torchring: { key: 'props-winter-a', frame: 0 },
  frozencorpse: { key: 'props-winter-a', frame: 1 },
  wallshard: { key: 'props-winter-a', frame: 2 },
  icesheet: { key: 'props-winter-a', frame: 3 },
  drift: { key: 'props-winter-a', frame: 4 },
  frozenwell: { key: 'props-winter-a', frame: 5 },
  pine: { key: 'props-winter-a', frame: 6 },
  sled: { key: 'props-winter-a', frame: 7 },
  icicle: { key: 'props-winter-a', frame: 8 },
  bellshrine: { key: 'props-winter-b', frame: 0 },
  frostcairn: { key: 'props-winter-b', frame: 1 },
  fountain: { key: 'props-winter-b', frame: 2 },
  buriedgate: { key: 'props-winter-b', frame: 3 },
  lantern: { key: 'props-winter-b', frame: 4 },
  webpatch: { key: 'props-winter-b', frame: 5 },
  bonetree: { key: 'props-winter-b', frame: 6 },
  stormstone: { key: 'props-winter-b', frame: 7 },
  'shrine-ice': { key: 'props-winter-b', frame: 8 },
  shard: { key: 'icons', frame: 0 },
  'relic-t1': { key: 'icons', frame: 1 },
  'relic-t2': { key: 'icons', frame: 2 },
  'relic-t3': { key: 'icons', frame: 3 },
  'relic-t4': { key: 'icons', frame: 4 },
  casket: { key: 'icons', frame: 5 },
  'gate-arrow': { key: 'icons', frame: 6 },
  pause: { key: 'icons', frame: 7 },
  'gear-blade': { key: 'icons', frame: 8 },
  'gear-shroud': { key: 'icons', frame: 9 },
  'gear-trinket': { key: 'icons', frame: 10 },
  'zone-castle': { key: 'icons', frame: 11 },
  'zone-outlands': { key: 'icons', frame: 12 },
  'zone-desert': { key: 'icons', frame: 13 },
  'zone-winter': { key: 'icons', frame: 14 },
  skull: { key: 'icons', frame: 15 },
} as const;

/**
 * UI chrome (panels, buttons, bar housings) is NOT art: it is drawn with
 * primitives in `ui/primitives.ts` so it adapts to any size and re-skins with
 * `PALETTE`. Generated art is used for content that is genuinely drawing —
 * icons, the title emblem, the backdrop and every entity.
 */

/** Animation keys, so gameplay code never types a string literal. */
export const ANIM = {
  heroIdle: 'hero-idle',
  heroRun: 'hero-run',
  heroHurt: 'hero-hurt',
  heroChannel: 'hero-channel',
  heroDeath: 'hero-death',
  heroExtract: 'hero-extract',
  wardenIdle: 'boss-warden-idle',
  wardenSweep: 'boss-warden-sweep',
  wardenSummon: 'boss-warden-summon',
  wardenEnrage: 'boss-warden-enrage',
  wardenDeath: 'boss-warden-death',
  wardenIdleOutlands: 'boss-warden-idle-outlands',
  wardenIdleDesert: 'boss-warden-idle-desert',
  wardenIdleWinter: 'boss-warden-idle-winter',
  shard: 'shard-glint',
  xpOrb: 'xp-mote',
  gateOpening: 'gate-opening',
  gateOpen: 'gate-open',
  gateClosing: 'gate-closing',
  collapseRing: 'collapse-ring',
} as const;
