import Phaser from 'phaser';
import { ICON, type ArtSlot } from '../data/art';
import { TEX } from '../core/keys';
import { GEAR_BASES, UNIQUES } from '../data/gear';
import { VALUABLES } from '../data/valuables';
import type { CharmId, ConsumableId, LootItem, WeaponId } from '../data/types-v2';

/**
 * One lookup from a PRD-V2 §11 icon id (`icon-wpn-bolt`, `icon-gear-sackcloth-hood`,
 * `mm-chest`, `icon-tab-vault`, `icon-cur-dust`, …) to something drawable.
 *
 * The registry (`data/art.ts ICON`) is regenerated by the integrator, so an id
 * can be absent from it, or present with its texture not loaded by the active
 * slice's art groups. Both cases degrade to a tinted procedural glyph from
 * `core/textures.ts` instead of a missing-texture box — never a crash.
 *
 * Shared by the run HUD (bag strip, quick-sheet, cards, pause, minimap) and the
 * hub scenes, so every surface resolves an item to the SAME art.
 */

type FallbackShape = 'disc' | 'square' | 'star' | 'ring';

const REGISTRY = ICON as Readonly<Record<string, ArtSlot | undefined>>;

/** The registry slot for `id`, only when its texture is actually loaded. */
export function iconSlot(scene: Phaser.Scene, id: string): ArtSlot | null {
  const slot = REGISTRY[id];
  if (slot !== undefined && scene.textures.exists(slot.key)) return slot;
  // Pre-regeneration path: the art agents name the sheet key after the id's
  // group, so a raw single-image texture keyed by the id itself also counts.
  if (scene.textures.exists(id)) return { key: id };
  return null;
}

/**
 * An icon image fitted into a `size`×`size` box (aspect kept), origin centre.
 * `fallbackTone` tints the procedural glyph used when the art is missing.
 */
export function iconFor(
  scene: Phaser.Scene,
  id: string,
  size: number,
  fallbackTone: number,
  fallbackShape: FallbackShape = 'disc',
): Phaser.GameObjects.Image {
  const slot = iconSlot(scene, id);
  if (slot !== null) {
    const img = scene.add.image(0, 0, slot.key, slot.frame);
    const scale = size / Math.max(1, Math.max(img.width, img.height));
    return img.setScale(scale);
  }
  const key = TEX[fallbackShape];
  const img = scene.textures.exists(key) ? scene.add.image(0, 0, key) : scene.add.image(0, 0, '__WHITE');
  img.setTint(fallbackTone);
  const scale = (size * 0.7) / Math.max(1, Math.max(img.width, img.height));
  return img.setScale(scale);
}

/** Re-points an existing icon image at `id` (pooled HUD slots); same fallback rules. */
export function setIcon(
  img: Phaser.GameObjects.Image,
  id: string,
  size: number,
  fallbackTone: number,
  fallbackShape: FallbackShape = 'disc',
): void {
  const slot = iconSlot(img.scene, id);
  if (slot !== null) {
    img.setTexture(slot.key, slot.frame).clearTint();
    img.setScale(size / Math.max(1, Math.max(img.frame.width, img.frame.height)));
    return;
  }
  const key = img.scene.textures.exists(TEX[fallbackShape]) ? TEX[fallbackShape] : '__WHITE';
  img.setTexture(key).setTint(fallbackTone);
  img.setScale((size * 0.7) / Math.max(1, Math.max(img.frame.width, img.frame.height)));
}

export function weaponIconId(id: WeaponId, evolved = false): string {
  return `${evolved ? 'icon-evo-' : 'icon-wpn-'}${id}`;
}

export function charmIconId(id: CharmId): string {
  return `icon-charm-${id}`;
}

export function beltIconId(id: ConsumableId): string {
  return `icon-cb-${id}`;
}

/** Gear base ids are the §5.15.2 names kebab-cased; uniques carry their own id. */
export function lootIconId(item: LootItem): string {
  if (item.kind === 'valuable') return `icon-val-${item.item.id}`;
  return item.item.unique !== undefined ? `icon-uniq-${item.item.unique}` : `icon-gear-${item.item.base}`;
}

/**
 * Draft card icon (`data/upgrades.ts` card ids): `w_unlock_<w>` / `w_boost_<w>`
 * → `icon-wpn-<w>`, `w_evo_<w>` → `icon-evo-<w>`, `ch_unlock_<c>` /
 * `ch_rank_<c>` → `icon-charm-<c>`; stat/effect/filler cards → `icon-card-<id>`.
 */
export function cardIconId(cardId: string): string {
  const m = /^(w_unlock_|w_boost_|w_evo_|ch_unlock_|ch_rank_)(.+)$/.exec(cardId);
  if (m === null) return `icon-card-${cardId}`;
  const [, prefix, rest] = m;
  if (prefix === 'w_evo_') return `icon-evo-${rest}`;
  return prefix?.startsWith('ch_') ? `icon-charm-${rest}` : `icon-wpn-${rest}`;
}

/** Player-facing item name (gear base / unique / valuable), never an id when data exists. */
export function lootName(item: LootItem): string {
  if (item.kind === 'valuable') return VALUABLES.find((v) => v.id === item.item.id)?.name ?? item.item.id;
  const g = item.item;
  if (g.unique !== undefined) return UNIQUES.find((u) => u.id === g.unique)?.name ?? g.unique;
  return GEAR_BASES.find((b) => b.id === g.base)?.name ?? g.base;
}
