// GENERATED by scripts/gen-art-registry.mjs — do not edit by hand; edit art/manifest.json + regenerate.
/**
 * Generated-art registry: the only place that knows asset paths and frame
 * geometry. Every sheet under `public/assets/generated/` was produced by the
 * `game-art` skill (native generate_image + sprite-forge export) against
 * `art/style.json`, so the whole set shares one style contract.
 *
 * Frame geometry and per-action scale come from each asset's
 * `sprite-metadata.json` and `art/manifest.json` — never hand-guessed. To
 * change a row here, edit the manifest (or re-export the asset) and re-run
 * `node scripts/gen-art-registry.mjs`.
 *
 * Pure data, no Phaser import.
 */

/**
 * How a slice's tuning points a gameplay role at loaded art: `{ key }` for a
 * single-image texture, `{ key, frame }` for one cell of a sheet (the shape
 * `ICON` entries already have). One declaration for every slice — a slot is
 * addressing art, which is what this registry is for.
 *
 * Resolve it once, at construction: when
 * `scene.textures.exists(slot.key)` is false the slice draws its procedural
 * fallback instead, so a pruned art group degrades instead of rendering
 * missing-texture boxes. Tint belongs to that fallback only — generated art
 * carries its own colour.
 */
export interface ArtSlot {
  /** Texture key from `TEXTURE`/`ANIM`/`ICON` (or a raw registry `key`). */
  key: string;
  /** Frame on a multi-frame sheet: index, or an atlas frame name. */
  frame?: string | number;
}

export interface SpriteAsset {
  /** Phaser texture key; also the animation key when `frames > 1`. */
  key: string;
  /**
   * `art/manifest.json` group this asset belongs to. `PreloadScene` loads a
   * row only when its group is listed in the active slice's `ART_GROUPS`, so a
   * game downloads the art its gameplay actually uses and nothing else.
   */
  group: string;
  /** Path under `public/`. */
  path: string;
  frameWidth: number;
  frameHeight: number;
  frames: number;
  /** ms per frame; ignored when `frames === 1`. */
  duration: number;
  loop: boolean;
  /**
   * Display-size compensation. Generated actions do not fill their cell to the
   * same height, so switching animation would visibly resize the character.
   * The entity multiplies its tuned size by this factor, which is
   * `baseActionHeight / thisActionHeight` (see `baseAction` in
   * art/manifest.json). Default 1.
   */
  scale?: number;
  /**
   * Which way the unflipped art faces. Some art reads as moving LEFT (cloak
   * trails right), so flipping on `velocity.x < 0` would face it backwards.
   * Default true.
   */
  facesRight?: boolean;
}

/** Animated sheets: loaded as spritesheets, one animation created per entry. */
export const SPRITES: readonly SpriteAsset[] = [
  // Template ICON names src reads (heart/star/coin/bolt, shield/skull/clock/levelUp), regenerated in the aurelia-retro-nasa style, same ids and cell order. Loaded as spritesheets so a frame index can be selected; no animation is created.
  { key: 'icons', group: 'ui', path: 'assets/generated/ui/icons/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },
  { key: 'icons-b', group: 'ui', path: 'assets/generated/ui/icons-b/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },

  // Extract + power buildings. hd-body, marker "scale":"fit", fit 0.9, align bottom, cellSize 256 (core 384). Mk II cut: Mk I sheet + runtime rank pips. Chroma guard off after export (rekey).
  { key: 'bld-drill-mk1', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-drill-mk1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-drill-mk3', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-drill-mk3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-borer-mk1', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-borer-mk1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-borer-mk3', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-borer-mk3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-harvester-mk1', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-harvester-mk1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-harvester-mk3', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-harvester-mk3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-venttap-mk1', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-venttap-mk1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-venttap-mk3', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-venttap-mk3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-sail-mk1', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-sail-mk1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-sail-mk3', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-sail-mk3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },

  // Process, logistics and housing buildings. Same conventions as buildings-a.
  { key: 'bld-farm-mk1', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-farm-mk1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-farm-mk3', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-farm-mk3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-smelter-mk1', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-smelter-mk1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-smelter-mk3', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-smelter-mk3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-cutter-mk1', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-cutter-mk1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-cutter-mk3', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-cutter-mk3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-foundry-mk1', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-foundry-mk1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'bld-foundry-mk3', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-foundry-mk3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },

  // Defense buildings + Beacon Spire. hd-body, marker "scale":"fit" (NOT scaleMode), fit 0.9, align bottom, cellSize 256; beacon + beacon-charging 384; walls fit 0.97 so segments butt side by side. Chroma guard off after export (rekey / process_raw).
  { key: 'bld-beacon-charging', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-beacon-charging/sprite-sheet.png', frameWidth: 384, frameHeight: 384, frames: 4, duration: 150, loop: true },

  // Selection ring is NOT generated: core/textures reticle (Graphics). scaffold/ruin: hd-body, frost: hd-fx; all "scale":"fit", fit 0.9, align bottom, componentMode all, 256 cells (3x3: 384). cracks: hd-fx 2x2 256 centre fit 0.86, frames 0-2 = crack-a/b/c, frame 3 spare. Frost is drawn over the dark building at alpha 0.6 (reviewed value). Loaded as spritesheets so a frame index can be selected; no animation is created.
  { key: 'state-cracks', group: 'building-states', path: 'assets/generated/building-states/state-cracks/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },

  // 2x2 patches, hd-fx centred fit 0.9, one shared sheet scale; frame index = purity (0 impure, 1 normal, 2 pure, 3 depleted). Loaded as spritesheets so a frame index can be selected; no animation is created.
  { key: 'dep-ore', group: 'deposits', path: 'assets/generated/deposits/dep-ore/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },
  { key: 'dep-ice', group: 'deposits', path: 'assets/generated/deposits/dep-ice/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },
  { key: 'dep-crystal', group: 'deposits', path: 'assets/generated/deposits/dep-crystal/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },
  { key: 'dep-vent', group: 'deposits', path: 'assets/generated/deposits/dep-vent/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },

  // 4 relic sites, one per cell, hd-fx centred. Loaded as spritesheets so a frame index can be selected; no animation is created.
  { key: 'relics', group: 'relics', path: 'assets/generated/relics/relics/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },

  // Full-bleed floor tiles (fullBleed + threshold 1 + edgeThreshold 1, xai frame stripped by deframe_bbox.py), L* 18-32. Blockers: hd-fx centred 3x3 sheets, frames 0-5 required, 6-8 spare. Loaded as spritesheets so a frame index can be selected; no animation is created.
  { key: 'steppe-blockers', group: 'terrain', path: 'assets/generated/terrain/steppe-blockers/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'rime-blockers', group: 'terrain', path: 'assets/generated/terrain/rime-blockers/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'ember-blockers', group: 'terrain', path: 'assets/generated/terrain/ember-blockers/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'nacre-blockers', group: 'terrain', path: 'assets/generated/terrain/nacre-blockers/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },

  // 112-kind budget as 3x3 hd-fx atlas sheets of single props (18 shared + 27 per biome), centred fit 0.86. Loaded as spritesheets so a frame index can be selected; no animation is created.
  { key: 'props-shared-0', group: 'world-props', path: 'assets/generated/world-props/props-shared-0/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-shared-1', group: 'world-props', path: 'assets/generated/world-props/props-shared-1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-steppe-0', group: 'world-props', path: 'assets/generated/world-props/props-steppe-0/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-steppe-1', group: 'world-props', path: 'assets/generated/world-props/props-steppe-1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-steppe-2', group: 'world-props', path: 'assets/generated/world-props/props-steppe-2/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-rime-0', group: 'world-props', path: 'assets/generated/world-props/props-rime-0/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-rime-1', group: 'world-props', path: 'assets/generated/world-props/props-rime-1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-rime-2', group: 'world-props', path: 'assets/generated/world-props/props-rime-2/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-ember-0', group: 'world-props', path: 'assets/generated/world-props/props-ember-0/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-ember-1', group: 'world-props', path: 'assets/generated/world-props/props-ember-1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-ember-2', group: 'world-props', path: 'assets/generated/world-props/props-ember-2/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-nacre-0', group: 'world-props', path: 'assets/generated/world-props/props-nacre-0/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-nacre-1', group: 'world-props', path: 'assets/generated/world-props/props-nacre-1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'props-nacre-2', group: 'world-props', path: 'assets/generated/world-props/props-nacre-2/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },

  // Walk = base (writeScaleProfile), attack binds it. Refit fit 0.86 align bottom (spitter 0.72, moth centre). Death sheets cut: chitin-shard burst + corpse fade.
  { key: 'fauna-skitter', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-skitter-walk/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: true },
  { key: 'fauna-skitter-attack', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-skitter-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'fauna-spitter', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-spitter-walk/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: true },
  { key: 'fauna-spitter-attack', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-spitter-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'fauna-brute', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-brute-walk/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: true },
  { key: 'fauna-brute-attack', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-brute-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'fauna-moth', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-moth-walk/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: true },
  { key: 'fauna-moth-attack', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-moth-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'fauna-grub', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-grub-walk/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: true },
  { key: 'fauna-grub-attack', group: 'fauna-a', path: 'assets/generated/fauna-a/fauna-grub-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },

  // Same as fauna-a (hd-body feet preserve); matron + titan on 512 cells, brood and stomp bind their walk profiles.
  { key: 'fauna-leech', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-leech-walk/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: true },
  { key: 'fauna-leech-attack', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-leech-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'fauna-bloat', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-bloat-walk/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: true },
  { key: 'fauna-bloat-attack', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-bloat-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'fauna-howler', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-howler-walk/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: true },
  { key: 'fauna-howler-attack', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-howler-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 100, loop: false },
  { key: 'fauna-matron', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-matron-walk/sprite-sheet.png', frameWidth: 512, frameHeight: 512, frames: 4, duration: 90, loop: true },
  { key: 'fauna-matron-attack', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-matron-attack/sprite-sheet.png', frameWidth: 512, frameHeight: 512, frames: 4, duration: 100, loop: false },
  { key: 'fauna-titan', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-titan-walk/sprite-sheet.png', frameWidth: 512, frameHeight: 512, frames: 4, duration: 90, loop: true },
  { key: 'fauna-titan-attack', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-titan-attack/sprite-sheet.png', frameWidth: 512, frameHeight: 512, frames: 4, duration: 100, loop: false },
  { key: 'fauna-matron-brood', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-matron-brood/sprite-sheet.png', frameWidth: 512, frameHeight: 512, frames: 4, duration: 120, loop: false },
  { key: 'fauna-titan-stomp', group: 'fauna-b', path: 'assets/generated/fauna-b/fauna-titan-stomp/sprite-sheet.png', frameWidth: 512, frameHeight: 512, frames: 4, duration: 120, loop: false },

  // Drone, lander shuttle (centred fit 0.9), Ark silhouette (hd-fx 512).
  { key: 'drone', group: 'colony-motion', path: 'assets/generated/colony-motion/drone/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: true },
  { key: 'lander-shuttle', group: 'colony-motion', path: 'assets/generated/colony-motion/lander-shuttle/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },

  // hd-fx 2x2 sheets, drawn with BlendModes.ADD. Field-edge glow and brownout flicker are runtime Graphics/tweens (core/textures), not generated.
  { key: 'fx-pulse-bolt', group: 'fx', path: 'assets/generated/fx/fx-pulse-bolt/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'fx-arc', group: 'fx', path: 'assets/generated/fx/fx-arc/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'fx-flak', group: 'fx', path: 'assets/generated/fx/fx-flak/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'fx-acid', group: 'fx', path: 'assets/generated/fx/fx-acid/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'fx-leech-sparks', group: 'fx', path: 'assets/generated/fx/fx-leech-sparks/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: true },
  { key: 'fx-bloat-burst', group: 'fx', path: 'assets/generated/fx/fx-bloat-burst/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'fx-frost-creep', group: 'fx', path: 'assets/generated/fx/fx-frost-creep/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'fx-beacon-beam', group: 'fx', path: 'assets/generated/fx/fx-beacon-beam/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: true },
  { key: 'fx-launch-flare', group: 'fx', path: 'assets/generated/fx/fx-launch-flare/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'fx-dusk-arrow', group: 'fx', path: 'assets/generated/fx/fx-dusk-arrow/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: true },
  { key: 'fx-build-dust', group: 'fx', path: 'assets/generated/fx/fx-build-dust/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'fx-upgrade-shine', group: 'fx', path: 'assets/generated/fx/fx-upgrade-shine/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },
  { key: 'fx-relic-burst', group: 'fx', path: 'assets/generated/fx/fx-relic-burst/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 80, loop: false },

  // 96px UI glyphs on 256 cells; goods, tags, alerts, kits, Ark branches, buildings. Loaded as spritesheets so a frame index can be selected; no animation is created.
  { key: 'icons-goods-a', group: 'icons-a', path: 'assets/generated/icons-a/icons-goods-a/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },
  { key: 'icons-goods-b', group: 'icons-a', path: 'assets/generated/icons-a/icons-goods-b/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-tags', group: 'icons-a', path: 'assets/generated/icons-a/icons-tags/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-alerts', group: 'icons-a', path: 'assets/generated/icons-a/icons-alerts/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-ark', group: 'icons-a', path: 'assets/generated/icons-a/icons-ark/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-bld-1', group: 'icons-a', path: 'assets/generated/icons-a/icons-bld-1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-bld-2', group: 'icons-a', path: 'assets/generated/icons-a/icons-bld-2/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-bld-3', group: 'icons-a', path: 'assets/generated/icons-a/icons-bld-3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },

  // Directive (36) and protocol (20) glyphs; tag frame drawn by ui primitives. Loaded as spritesheets so a frame index can be selected; no animation is created.
  { key: 'icons-dir-1', group: 'icons-b', path: 'assets/generated/icons-b/icons-dir-1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-dir-2', group: 'icons-b', path: 'assets/generated/icons-b/icons-dir-2/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-dir-3', group: 'icons-b', path: 'assets/generated/icons-b/icons-dir-3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-dir-4', group: 'icons-b', path: 'assets/generated/icons-b/icons-dir-4/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-proto-1', group: 'icons-b', path: 'assets/generated/icons-b/icons-proto-1/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-proto-2', group: 'icons-b', path: 'assets/generated/icons-b/icons-proto-2/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
  { key: 'icons-proto-3', group: 'icons-b', path: 'assets/generated/icons-b/icons-proto-3/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 9, duration: 0, loop: false },
] as const;

/** Single-image textures: no animation, no frame slicing. */
export const IMAGES: readonly SpriteAsset[] = [
  // arena = dusk Aurelia sky backdrop, full-bleed 720x1280 (9:16), strict + fullBleed; logo = OUTPOST AURELIA wordmark (stacked) over a dome emblem, 512 cell, re-keyed.
  { key: 'bg-arena', group: 'bg', path: 'assets/generated/bg/arena/sprite.png', frameWidth: 720, frameHeight: 1280, frames: 1, duration: 0, loop: false },
  { key: 'logo', group: 'bg', path: 'assets/generated/bg/logo/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },

  // Extract + power buildings. hd-body, marker "scale":"fit", fit 0.9, align bottom, cellSize 256 (core 384). Mk II cut: Mk I sheet + runtime rank pips. Chroma guard off after export (rekey).
  { key: 'bld-core', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-core/sprite.png', frameWidth: 384, frameHeight: 384, frames: 1, duration: 0, loop: false },
  { key: 'bld-bank-mk1', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-bank-mk1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-bank-mk3', group: 'buildings-a', path: 'assets/generated/buildings-a/bld-bank-mk3/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },

  // Process, logistics and housing buildings. Same conventions as buildings-a.
  { key: 'bld-relay-mk1', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-relay-mk1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-relay-mk3', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-relay-mk3/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-silo-mk1', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-silo-mk1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-silo-mk3', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-silo-mk3/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-hab-mk1', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-hab-mk1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-hab-mk3', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-hab-mk3/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-commons-mk1', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-commons-mk1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-commons-mk3', group: 'buildings-b', path: 'assets/generated/buildings-b/bld-commons-mk3/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },

  // Defense buildings + Beacon Spire. hd-body, marker "scale":"fit" (NOT scaleMode), fit 0.9, align bottom, cellSize 256; beacon + beacon-charging 384; walls fit 0.97 so segments butt side by side. Chroma guard off after export (rekey / process_raw).
  { key: 'bld-pulse-mk1', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-pulse-mk1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-pulse-mk3', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-pulse-mk3/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-arc-mk1', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-arc-mk1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-arc-mk3', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-arc-mk3/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-flak-mk1', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-flak-mk1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-flak-mk3', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-flak-mk3/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-wall-mk1', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-wall-mk1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-wall-mk3', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-wall-mk3/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-beacon', group: 'buildings-c', path: 'assets/generated/buildings-c/bld-beacon/sprite.png', frameWidth: 384, frameHeight: 384, frames: 1, duration: 0, loop: false },

  // Mk IV protocol variants. Image 1 = single-frame Mk III crop flattened on #FF00FF (or text-only when Image 1 was copied), Image 2 = vision anchor. hd-body, marker "scale":"fit", fit 0.9 (wall 0.97), align bottom, cellSize 256 (beacon 384), threshold 150, chroma guard off. badge-silent: hd-fx centred 256.
  { key: 'bld-hab-apex', group: 'apex', path: 'assets/generated/apex/bld-hab-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-pulse-apex', group: 'apex', path: 'assets/generated/apex/bld-pulse-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-wall-apex', group: 'apex', path: 'assets/generated/apex/bld-wall-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-smelter-apex', group: 'apex', path: 'assets/generated/apex/bld-smelter-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-relay-apex', group: 'apex', path: 'assets/generated/apex/bld-relay-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-venttap-apex', group: 'apex', path: 'assets/generated/apex/bld-venttap-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-bank-apex', group: 'apex', path: 'assets/generated/apex/bld-bank-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-sail-apex', group: 'apex', path: 'assets/generated/apex/bld-sail-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-arc-apex', group: 'apex', path: 'assets/generated/apex/bld-arc-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-flak-apex', group: 'apex', path: 'assets/generated/apex/bld-flak-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-cutter-apex', group: 'apex', path: 'assets/generated/apex/bld-cutter-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-foundry-apex', group: 'apex', path: 'assets/generated/apex/bld-foundry-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-harvester-apex', group: 'apex', path: 'assets/generated/apex/bld-harvester-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-commons-apex', group: 'apex', path: 'assets/generated/apex/bld-commons-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'bld-beacon-apex', group: 'apex', path: 'assets/generated/apex/bld-beacon-apex/sprite.png', frameWidth: 384, frameHeight: 384, frames: 1, duration: 0, loop: false },
  { key: 'bld-silo-apex', group: 'apex', path: 'assets/generated/apex/bld-silo-apex/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'badge-silent', group: 'apex', path: 'assets/generated/apex/badge-silent/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },

  // Selection ring is NOT generated: core/textures reticle (Graphics). scaffold/ruin: hd-body, frost: hd-fx; all "scale":"fit", fit 0.9, align bottom, componentMode all, 256 cells (3x3: 384). cracks: hd-fx 2x2 256 centre fit 0.86, frames 0-2 = crack-a/b/c, frame 3 spare. Frost is drawn over the dark building at alpha 0.6 (reviewed value).
  { key: 'state-scaffold-1x1', group: 'building-states', path: 'assets/generated/building-states/state-scaffold-1x1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'state-ruin-1x1', group: 'building-states', path: 'assets/generated/building-states/state-ruin-1x1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'state-frost-1x1', group: 'building-states', path: 'assets/generated/building-states/state-frost-1x1/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'state-scaffold-2x2', group: 'building-states', path: 'assets/generated/building-states/state-scaffold-2x2/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'state-ruin-2x2', group: 'building-states', path: 'assets/generated/building-states/state-ruin-2x2/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'state-frost-2x2', group: 'building-states', path: 'assets/generated/building-states/state-frost-2x2/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'state-scaffold-3x3', group: 'building-states', path: 'assets/generated/building-states/state-scaffold-3x3/sprite.png', frameWidth: 384, frameHeight: 384, frames: 1, duration: 0, loop: false },
  { key: 'state-ruin-3x3', group: 'building-states', path: 'assets/generated/building-states/state-ruin-3x3/sprite.png', frameWidth: 384, frameHeight: 384, frames: 1, duration: 0, loop: false },
  { key: 'state-frost-3x3', group: 'building-states', path: 'assets/generated/building-states/state-frost-3x3/sprite.png', frameWidth: 384, frameHeight: 384, frames: 1, duration: 0, loop: false },

  // Full-bleed floor tiles (fullBleed + threshold 1 + edgeThreshold 1, xai frame stripped by deframe_bbox.py), L* 18-32. Blockers: hd-fx centred 3x3 sheets, frames 0-5 required, 6-8 spare.
  { key: 'steppe-floor-a', group: 'terrain', path: 'assets/generated/terrain/steppe-floor-a/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'steppe-floor-b', group: 'terrain', path: 'assets/generated/terrain/steppe-floor-b/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'steppe-floor-c', group: 'terrain', path: 'assets/generated/terrain/steppe-floor-c/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'rime-floor-a', group: 'terrain', path: 'assets/generated/terrain/rime-floor-a/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'rime-floor-b', group: 'terrain', path: 'assets/generated/terrain/rime-floor-b/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'rime-floor-c', group: 'terrain', path: 'assets/generated/terrain/rime-floor-c/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'ember-floor-a', group: 'terrain', path: 'assets/generated/terrain/ember-floor-a/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'ember-floor-b', group: 'terrain', path: 'assets/generated/terrain/ember-floor-b/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'ember-floor-c', group: 'terrain', path: 'assets/generated/terrain/ember-floor-c/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'nacre-floor-a', group: 'terrain', path: 'assets/generated/terrain/nacre-floor-a/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'nacre-floor-b', group: 'terrain', path: 'assets/generated/terrain/nacre-floor-b/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'nacre-floor-c', group: 'terrain', path: 'assets/generated/terrain/nacre-floor-c/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },

  // Drone, lander shuttle (centred fit 0.9), Ark silhouette (hd-fx 512).
  { key: 'ark-silhouette', group: 'colony-motion', path: 'assets/generated/colony-motion/ark-silhouette/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },

  // Full-bleed hub art; planet map portrait 720x900, postcards 600x360. Generated marker-less and processed by art/exports/hub/fitcrop.py (process-sprite --full-bleed --strict). Site-node centres: art/briefs/reports/hub.md.
  { key: 'hub-planet-map', group: 'hub', path: 'assets/generated/hub/hub-planet-map/sprite.png', frameWidth: 720, frameHeight: 900, frames: 1, duration: 0, loop: false },
  { key: 'postcard-halcyon', group: 'hub', path: 'assets/generated/hub/postcard-halcyon/sprite.png', frameWidth: 600, frameHeight: 360, frames: 1, duration: 0, loop: false },
  { key: 'postcard-prism_reach', group: 'hub', path: 'assets/generated/hub/postcard-prism_reach/sprite.png', frameWidth: 600, frameHeight: 360, frames: 1, duration: 0, loop: false },
  { key: 'postcard-rimewater', group: 'hub', path: 'assets/generated/hub/postcard-rimewater/sprite.png', frameWidth: 600, frameHeight: 360, frames: 1, duration: 0, loop: false },
  { key: 'postcard-cinder_fen', group: 'hub', path: 'assets/generated/hub/postcard-cinder_fen/sprite.png', frameWidth: 600, frameHeight: 360, frames: 1, duration: 0, loop: false },
  { key: 'postcard-frostcrown', group: 'hub', path: 'assets/generated/hub/postcard-frostcrown/sprite.png', frameWidth: 600, frameHeight: 360, frames: 1, duration: 0, loop: false },
  { key: 'postcard-sulfur_hollow', group: 'hub', path: 'assets/generated/hub/postcard-sulfur_hollow/sprite.png', frameWidth: 600, frameHeight: 360, frames: 1, duration: 0, loop: false },
  { key: 'postcard-nacre_shelf', group: 'hub', path: 'assets/generated/hub/postcard-nacre_shelf/sprite.png', frameWidth: 600, frameHeight: 360, frames: 1, duration: 0, loop: false },
  { key: 'postcard-aurora_rift', group: 'hub', path: 'assets/generated/hub/postcard-aurora_rift/sprite.png', frameWidth: 600, frameHeight: 360, frames: 1, duration: 0, loop: false },
] as const;

const BY_KEY: Record<string, SpriteAsset> = {};
for (const asset of SPRITES) BY_KEY[asset.key] = asset;

/** Display-size factor for an animation key (1 when the asset needs none). */
export function artScale(key: string): number {
  return BY_KEY[key]?.scale ?? 1;
}

/** True when the unflipped art faces right. */
export function artFacesRight(key: string): boolean {
  return BY_KEY[key]?.facesRight ?? true;
}

/** Static texture keys, so gameplay code never types a string literal. */
export const TEXTURE = {
  backdrop: 'bg-arena',
  logo: 'logo',
} as const;

/** Frame index per icon inside the icon sheets. */
export const ICON = {
  heart: { key: 'icons', frame: 0 },
  star: { key: 'icons', frame: 1 },
  coin: { key: 'icons', frame: 2 },
  bolt: { key: 'icons', frame: 3 },
  shield: { key: 'icons-b', frame: 0 },
  skull: { key: 'icons-b', frame: 1 },
  clock: { key: 'icons-b', frame: 2 },
  levelUp: { key: 'icons-b', frame: 3 },
  'crack-a': { key: 'state-cracks', frame: 0 },
  'crack-b': { key: 'state-cracks', frame: 1 },
  'crack-c': { key: 'state-cracks', frame: 2 },
  'dep-ore-0': { key: 'dep-ore', frame: 0 },
  'dep-ore-1': { key: 'dep-ore', frame: 1 },
  'dep-ore-2': { key: 'dep-ore', frame: 2 },
  'dep-ore-x': { key: 'dep-ore', frame: 3 },
  'dep-ice-0': { key: 'dep-ice', frame: 0 },
  'dep-ice-1': { key: 'dep-ice', frame: 1 },
  'dep-ice-2': { key: 'dep-ice', frame: 2 },
  'dep-ice-x': { key: 'dep-ice', frame: 3 },
  'dep-crystal-0': { key: 'dep-crystal', frame: 0 },
  'dep-crystal-1': { key: 'dep-crystal', frame: 1 },
  'dep-crystal-2': { key: 'dep-crystal', frame: 2 },
  'dep-crystal-x': { key: 'dep-crystal', frame: 3 },
  'dep-vent-0': { key: 'dep-vent', frame: 0 },
  'dep-vent-1': { key: 'dep-vent', frame: 1 },
  'dep-vent-2': { key: 'dep-vent', frame: 2 },
  'dep-vent-x': { key: 'dep-vent', frame: 3 },
  'relic-probe': { key: 'relics', frame: 0 },
  'relic-monolith': { key: 'relics', frame: 1 },
  'relic-buoy': { key: 'relics', frame: 2 },
  'relic-geode': { key: 'relics', frame: 3 },
  'steppe-block-1': { key: 'steppe-blockers', frame: 0 },
  'steppe-block-2': { key: 'steppe-blockers', frame: 1 },
  'steppe-block-3': { key: 'steppe-blockers', frame: 2 },
  'steppe-block-4': { key: 'steppe-blockers', frame: 3 },
  'steppe-block-5': { key: 'steppe-blockers', frame: 4 },
  'steppe-block-6': { key: 'steppe-blockers', frame: 5 },
  'steppe-block-7': { key: 'steppe-blockers', frame: 6 },
  'steppe-block-8': { key: 'steppe-blockers', frame: 7 },
  'steppe-block-9': { key: 'steppe-blockers', frame: 8 },
  'rime-block-1': { key: 'rime-blockers', frame: 0 },
  'rime-block-2': { key: 'rime-blockers', frame: 1 },
  'rime-block-3': { key: 'rime-blockers', frame: 2 },
  'rime-block-4': { key: 'rime-blockers', frame: 3 },
  'rime-block-5': { key: 'rime-blockers', frame: 4 },
  'rime-block-6': { key: 'rime-blockers', frame: 5 },
  'rime-block-7': { key: 'rime-blockers', frame: 6 },
  'rime-block-8': { key: 'rime-blockers', frame: 7 },
  'rime-block-9': { key: 'rime-blockers', frame: 8 },
  'ember-block-1': { key: 'ember-blockers', frame: 0 },
  'ember-block-2': { key: 'ember-blockers', frame: 1 },
  'ember-block-3': { key: 'ember-blockers', frame: 2 },
  'ember-block-4': { key: 'ember-blockers', frame: 3 },
  'ember-block-5': { key: 'ember-blockers', frame: 4 },
  'ember-block-6': { key: 'ember-blockers', frame: 5 },
  'ember-block-7': { key: 'ember-blockers', frame: 6 },
  'ember-block-8': { key: 'ember-blockers', frame: 7 },
  'ember-block-9': { key: 'ember-blockers', frame: 8 },
  'nacre-block-1': { key: 'nacre-blockers', frame: 0 },
  'nacre-block-2': { key: 'nacre-blockers', frame: 1 },
  'nacre-block-3': { key: 'nacre-blockers', frame: 2 },
  'nacre-block-4': { key: 'nacre-blockers', frame: 3 },
  'nacre-block-5': { key: 'nacre-blockers', frame: 4 },
  'nacre-block-6': { key: 'nacre-blockers', frame: 5 },
  'nacre-block-7': { key: 'nacre-blockers', frame: 6 },
  'nacre-block-8': { key: 'nacre-blockers', frame: 7 },
  'nacre-block-9': { key: 'nacre-blockers', frame: 8 },
  'prop-shared-1': { key: 'props-shared-0', frame: 0 },
  'prop-shared-2': { key: 'props-shared-0', frame: 1 },
  'prop-shared-3': { key: 'props-shared-0', frame: 2 },
  'prop-shared-4': { key: 'props-shared-0', frame: 3 },
  'prop-shared-5': { key: 'props-shared-0', frame: 4 },
  'prop-shared-6': { key: 'props-shared-0', frame: 5 },
  'prop-shared-7': { key: 'props-shared-0', frame: 6 },
  'prop-shared-8': { key: 'props-shared-0', frame: 7 },
  'prop-shared-9': { key: 'props-shared-0', frame: 8 },
  'prop-shared-10': { key: 'props-shared-1', frame: 0 },
  'prop-shared-11': { key: 'props-shared-1', frame: 1 },
  'prop-shared-12': { key: 'props-shared-1', frame: 2 },
  'prop-shared-13': { key: 'props-shared-1', frame: 3 },
  'prop-shared-14': { key: 'props-shared-1', frame: 4 },
  'prop-shared-15': { key: 'props-shared-1', frame: 5 },
  'prop-shared-16': { key: 'props-shared-1', frame: 6 },
  'prop-shared-17': { key: 'props-shared-1', frame: 7 },
  'prop-shared-18': { key: 'props-shared-1', frame: 8 },
  'prop-steppe-1': { key: 'props-steppe-0', frame: 0 },
  'prop-steppe-2': { key: 'props-steppe-0', frame: 1 },
  'prop-steppe-3': { key: 'props-steppe-0', frame: 2 },
  'prop-steppe-4': { key: 'props-steppe-0', frame: 3 },
  'prop-steppe-5': { key: 'props-steppe-0', frame: 4 },
  'prop-steppe-6': { key: 'props-steppe-0', frame: 5 },
  'prop-steppe-7': { key: 'props-steppe-0', frame: 6 },
  'prop-steppe-8': { key: 'props-steppe-0', frame: 7 },
  'prop-steppe-9': { key: 'props-steppe-0', frame: 8 },
  'prop-steppe-10': { key: 'props-steppe-1', frame: 0 },
  'prop-steppe-11': { key: 'props-steppe-1', frame: 1 },
  'prop-steppe-12': { key: 'props-steppe-1', frame: 2 },
  'prop-steppe-13': { key: 'props-steppe-1', frame: 3 },
  'prop-steppe-14': { key: 'props-steppe-1', frame: 4 },
  'prop-steppe-15': { key: 'props-steppe-1', frame: 5 },
  'prop-steppe-16': { key: 'props-steppe-1', frame: 6 },
  'prop-steppe-17': { key: 'props-steppe-1', frame: 7 },
  'prop-steppe-18': { key: 'props-steppe-1', frame: 8 },
  'prop-steppe-19': { key: 'props-steppe-2', frame: 0 },
  'prop-steppe-20': { key: 'props-steppe-2', frame: 1 },
  'prop-steppe-21': { key: 'props-steppe-2', frame: 2 },
  'prop-steppe-22': { key: 'props-steppe-2', frame: 3 },
  'prop-steppe-23': { key: 'props-steppe-2', frame: 4 },
  'prop-steppe-24': { key: 'props-steppe-2', frame: 5 },
  'prop-steppe-25': { key: 'props-steppe-2', frame: 6 },
  'prop-steppe-26': { key: 'props-steppe-2', frame: 7 },
  'prop-steppe-27': { key: 'props-steppe-2', frame: 8 },
  'prop-rime-1': { key: 'props-rime-0', frame: 0 },
  'prop-rime-2': { key: 'props-rime-0', frame: 1 },
  'prop-rime-3': { key: 'props-rime-0', frame: 2 },
  'prop-rime-4': { key: 'props-rime-0', frame: 3 },
  'prop-rime-5': { key: 'props-rime-0', frame: 4 },
  'prop-rime-6': { key: 'props-rime-0', frame: 5 },
  'prop-rime-7': { key: 'props-rime-0', frame: 6 },
  'prop-rime-8': { key: 'props-rime-0', frame: 7 },
  'prop-rime-9': { key: 'props-rime-0', frame: 8 },
  'prop-rime-10': { key: 'props-rime-1', frame: 0 },
  'prop-rime-11': { key: 'props-rime-1', frame: 1 },
  'prop-rime-12': { key: 'props-rime-1', frame: 2 },
  'prop-rime-13': { key: 'props-rime-1', frame: 3 },
  'prop-rime-14': { key: 'props-rime-1', frame: 4 },
  'prop-rime-15': { key: 'props-rime-1', frame: 5 },
  'prop-rime-16': { key: 'props-rime-1', frame: 6 },
  'prop-rime-17': { key: 'props-rime-1', frame: 7 },
  'prop-rime-18': { key: 'props-rime-1', frame: 8 },
  'prop-rime-19': { key: 'props-rime-2', frame: 0 },
  'prop-rime-20': { key: 'props-rime-2', frame: 1 },
  'prop-rime-21': { key: 'props-rime-2', frame: 2 },
  'prop-rime-22': { key: 'props-rime-2', frame: 3 },
  'prop-rime-23': { key: 'props-rime-2', frame: 4 },
  'prop-rime-24': { key: 'props-rime-2', frame: 5 },
  'prop-rime-25': { key: 'props-rime-2', frame: 6 },
  'prop-rime-26': { key: 'props-rime-2', frame: 7 },
  'prop-rime-27': { key: 'props-rime-2', frame: 8 },
  'prop-ember-1': { key: 'props-ember-0', frame: 0 },
  'prop-ember-2': { key: 'props-ember-0', frame: 1 },
  'prop-ember-3': { key: 'props-ember-0', frame: 2 },
  'prop-ember-4': { key: 'props-ember-0', frame: 3 },
  'prop-ember-5': { key: 'props-ember-0', frame: 4 },
  'prop-ember-6': { key: 'props-ember-0', frame: 5 },
  'prop-ember-7': { key: 'props-ember-0', frame: 6 },
  'prop-ember-8': { key: 'props-ember-0', frame: 7 },
  'prop-ember-9': { key: 'props-ember-0', frame: 8 },
  'prop-ember-10': { key: 'props-ember-1', frame: 0 },
  'prop-ember-11': { key: 'props-ember-1', frame: 1 },
  'prop-ember-12': { key: 'props-ember-1', frame: 2 },
  'prop-ember-13': { key: 'props-ember-1', frame: 3 },
  'prop-ember-14': { key: 'props-ember-1', frame: 4 },
  'prop-ember-15': { key: 'props-ember-1', frame: 5 },
  'prop-ember-16': { key: 'props-ember-1', frame: 6 },
  'prop-ember-17': { key: 'props-ember-1', frame: 7 },
  'prop-ember-18': { key: 'props-ember-1', frame: 8 },
  'prop-ember-19': { key: 'props-ember-2', frame: 0 },
  'prop-ember-20': { key: 'props-ember-2', frame: 1 },
  'prop-ember-21': { key: 'props-ember-2', frame: 2 },
  'prop-ember-22': { key: 'props-ember-2', frame: 3 },
  'prop-ember-23': { key: 'props-ember-2', frame: 4 },
  'prop-ember-24': { key: 'props-ember-2', frame: 5 },
  'prop-ember-25': { key: 'props-ember-2', frame: 6 },
  'prop-ember-26': { key: 'props-ember-2', frame: 7 },
  'prop-ember-27': { key: 'props-ember-2', frame: 8 },
  'prop-nacre-1': { key: 'props-nacre-0', frame: 0 },
  'prop-nacre-2': { key: 'props-nacre-0', frame: 1 },
  'prop-nacre-3': { key: 'props-nacre-0', frame: 2 },
  'prop-nacre-4': { key: 'props-nacre-0', frame: 3 },
  'prop-nacre-5': { key: 'props-nacre-0', frame: 4 },
  'prop-nacre-6': { key: 'props-nacre-0', frame: 5 },
  'prop-nacre-7': { key: 'props-nacre-0', frame: 6 },
  'prop-nacre-8': { key: 'props-nacre-0', frame: 7 },
  'prop-nacre-9': { key: 'props-nacre-0', frame: 8 },
  'prop-nacre-10': { key: 'props-nacre-1', frame: 0 },
  'prop-nacre-11': { key: 'props-nacre-1', frame: 1 },
  'prop-nacre-12': { key: 'props-nacre-1', frame: 2 },
  'prop-nacre-13': { key: 'props-nacre-1', frame: 3 },
  'prop-nacre-14': { key: 'props-nacre-1', frame: 4 },
  'prop-nacre-15': { key: 'props-nacre-1', frame: 5 },
  'prop-nacre-16': { key: 'props-nacre-1', frame: 6 },
  'prop-nacre-17': { key: 'props-nacre-1', frame: 7 },
  'prop-nacre-18': { key: 'props-nacre-1', frame: 8 },
  'prop-nacre-19': { key: 'props-nacre-2', frame: 0 },
  'prop-nacre-20': { key: 'props-nacre-2', frame: 1 },
  'prop-nacre-21': { key: 'props-nacre-2', frame: 2 },
  'prop-nacre-22': { key: 'props-nacre-2', frame: 3 },
  'prop-nacre-23': { key: 'props-nacre-2', frame: 4 },
  'prop-nacre-24': { key: 'props-nacre-2', frame: 5 },
  'prop-nacre-25': { key: 'props-nacre-2', frame: 6 },
  'prop-nacre-26': { key: 'props-nacre-2', frame: 7 },
  'prop-nacre-27': { key: 'props-nacre-2', frame: 8 },
  ferrite: { key: 'icons-goods-a', frame: 0 },
  ice: { key: 'icons-goods-a', frame: 1 },
  aurelite: { key: 'icons-goods-a', frame: 2 },
  alloy: { key: 'icons-goods-a', frame: 3 },
  rations: { key: 'icons-goods-b', frame: 0 },
  prism: { key: 'icons-goods-b', frame: 1 },
  cell: { key: 'icons-goods-b', frame: 2 },
  power: { key: 'icons-goods-b', frame: 3 },
  colonists: { key: 'icons-goods-b', frame: 4 },
  morale: { key: 'icons-goods-b', frame: 5 },
  temperature: { key: 'icons-goods-b', frame: 6 },
  data: { key: 'icons-goods-b', frame: 7 },
  reroll: { key: 'icons-goods-b', frame: 8 },
  'tag-hearth': { key: 'icons-tags', frame: 0 },
  'tag-forge': { key: 'icons-tags', frame: 1 },
  'tag-bul': { key: 'icons-tags', frame: 2 },
  'tag-fr': { key: 'icons-tags', frame: 3 },
  'tag-kin': { key: 'icons-tags', frame: 4 },
  'tag-orb': { key: 'icons-tags', frame: 5 },
  'alert-relay-dark': { key: 'icons-tags', frame: 6 },
  'alert-hab-cold': { key: 'icons-tags', frame: 7 },
  'alert-leech': { key: 'icons-tags', frame: 8 },
  'alert-order-ready': { key: 'icons-alerts', frame: 0 },
  'alert-idle-crew': { key: 'icons-alerts', frame: 1 },
  'alert-starving': { key: 'icons-alerts', frame: 2 },
  'alert-core-hit': { key: 'icons-alerts', frame: 3 },
  'alert-alpha': { key: 'icons-alerts', frame: 4 },
  'kit-engineer': { key: 'icons-alerts', frame: 5 },
  'kit-warden': { key: 'icons-alerts', frame: 6 },
  'kit-settler': { key: 'icons-alerts', frame: 7 },
  'kit-surveyor': { key: 'icons-alerts', frame: 8 },
  'kit-tinker': { key: 'icons-ark', frame: 0 },
  'ark-hab': { key: 'icons-ark', frame: 1 },
  'ark-forge': { key: 'icons-ark', frame: 2 },
  'ark-grid': { key: 'icons-ark', frame: 3 },
  'ark-bul': { key: 'icons-ark', frame: 4 },
  'ark-sur': { key: 'icons-ark', frame: 5 },
  'ark-cmd': { key: 'icons-ark', frame: 6 },
  'ark-ship': { key: 'icons-ark', frame: 7 },
  'ark-locked': { key: 'icons-ark', frame: 8 },
  'ico-core': { key: 'icons-bld-1', frame: 0 },
  'ico-drill': { key: 'icons-bld-1', frame: 1 },
  'ico-borer': { key: 'icons-bld-1', frame: 2 },
  'ico-harvester': { key: 'icons-bld-1', frame: 3 },
  'ico-venttap': { key: 'icons-bld-1', frame: 4 },
  'ico-sail': { key: 'icons-bld-1', frame: 5 },
  'ico-bank': { key: 'icons-bld-1', frame: 6 },
  'ico-farm': { key: 'icons-bld-1', frame: 7 },
  'ico-smelter': { key: 'icons-bld-1', frame: 8 },
  'ico-cutter': { key: 'icons-bld-2', frame: 0 },
  'ico-foundry': { key: 'icons-bld-2', frame: 1 },
  'ico-relay': { key: 'icons-bld-2', frame: 2 },
  'ico-silo': { key: 'icons-bld-2', frame: 3 },
  'ico-hab': { key: 'icons-bld-2', frame: 4 },
  'ico-commons': { key: 'icons-bld-2', frame: 5 },
  'ico-pulse': { key: 'icons-bld-2', frame: 6 },
  'ico-arc': { key: 'icons-bld-2', frame: 7 },
  'ico-flak': { key: 'icons-bld-2', frame: 8 },
  'ico-wall': { key: 'icons-bld-3', frame: 0 },
  'ico-beacon': { key: 'icons-bld-3', frame: 1 },
  'ico-upgrade': { key: 'icons-bld-3', frame: 2 },
  'ico-demolish': { key: 'icons-bld-3', frame: 3 },
  'dir-hearth_insulate': { key: 'icons-dir-1', frame: 0 },
  'dir-hearth_overdrive': { key: 'icons-dir-1', frame: 1 },
  'dir-hearth_battery': { key: 'icons-dir-1', frame: 2 },
  'dir-hearth_vents': { key: 'icons-dir-1', frame: 3 },
  'dir-hearth_sunward': { key: 'icons-dir-1', frame: 4 },
  'dir-hearth_dimming': { key: 'icons-dir-1', frame: 5 },
  'dir-forge_quota': { key: 'icons-dir-1', frame: 6 },
  'dir-forge_parts': { key: 'icons-dir-1', frame: 7 },
  'dir-forge_assay': { key: 'icons-dir-1', frame: 8 },
  'dir-forge_pour': { key: 'icons-dir-2', frame: 0 },
  'dir-forge_lens': { key: 'icons-dir-2', frame: 1 },
  'dir-forge_cell': { key: 'icons-dir-2', frame: 2 },
  'dir-bul_plate': { key: 'icons-dir-2', frame: 3 },
  'dir-bul_pulse': { key: 'icons-dir-2', frame: 4 },
  'dir-bul_arc': { key: 'icons-dir-2', frame: 5 },
  'dir-bul_flak': { key: 'icons-dir-2', frame: 6 },
  'dir-bul_mend': { key: 'icons-dir-2', frame: 7 },
  'dir-bul_salvage': { key: 'icons-dir-2', frame: 8 },
  'dir-fr_relay': { key: 'icons-dir-3', frame: 0 },
  'dir-fr_survey': { key: 'icons-dir-3', frame: 1 },
  'dir-fr_prefab': { key: 'icons-dir-3', frame: 2 },
  'dir-fr_muffle': { key: 'icons-dir-3', frame: 3 },
  'dir-fr_sentry': { key: 'icons-dir-3', frame: 4 },
  'dir-fr_claim': { key: 'icons-dir-3', frame: 5 },
  'dir-kin_hatch': { key: 'icons-dir-3', frame: 6 },
  'dir-kin_lean': { key: 'icons-dir-3', frame: 7 },
  'dir-kin_songs': { key: 'icons-dir-3', frame: 8 },
  'dir-kin_medics': { key: 'icons-dir-4', frame: 0 },
  'dir-kin_rota': { key: 'icons-dir-4', frame: 1 },
  'dir-kin_pact': { key: 'icons-dir-4', frame: 2 },
  'dir-orb_manifest': { key: 'icons-dir-4', frame: 3 },
  'dir-orb_pods': { key: 'icons-dir-4', frame: 4 },
  'dir-orb_resonant': { key: 'icons-dir-4', frame: 5 },
  'dir-orb_band': { key: 'icons-dir-4', frame: 6 },
  'dir-orb_decoy': { key: 'icons-dir-4', frame: 7 },
  'dir-orb_window': { key: 'icons-dir-4', frame: 8 },
  'proto-p_warren': { key: 'icons-proto-1', frame: 0 },
  'proto-p_lattice': { key: 'icons-proto-1', frame: 1 },
  'proto-p_bastion': { key: 'icons-proto-1', frame: 2 },
  'proto-p_crucible': { key: 'icons-proto-1', frame: 3 },
  'proto-p_halo': { key: 'icons-proto-1', frame: 4 },
  'proto-p_plaza': { key: 'icons-proto-1', frame: 5 },
  'proto-p_magma': { key: 'icons-proto-1', frame: 6 },
  'proto-p_vault': { key: 'icons-proto-1', frame: 7 },
  'proto-p_aurora': { key: 'icons-proto-1', frame: 8 },
  'proto-p_storm': { key: 'icons-proto-2', frame: 0 },
  'proto-p_sky': { key: 'icons-proto-2', frame: 1 },
  'proto-p_living': { key: 'icons-proto-2', frame: 2 },
  'proto-p_slag': { key: 'icons-proto-2', frame: 3 },
  'proto-p_focus': { key: 'icons-proto-2', frame: 4 },
  'proto-p_lumen': { key: 'icons-proto-2', frame: 5 },
  'proto-p_silent': { key: 'icons-proto-2', frame: 6 },
  'proto-p_geode': { key: 'icons-proto-2', frame: 7 },
  'proto-p_infirm': { key: 'icons-proto-2', frame: 8 },
  'proto-p_choir': { key: 'icons-proto-3', frame: 0 },
  'proto-p_exchange': { key: 'icons-proto-3', frame: 1 },
} as const;

/**
 * UI chrome (panels, buttons, bar housings) is NOT art: it is drawn with
 * primitives in `ui/primitives.ts` so it adapts to any size and re-skins with
 * `PALETTE`. Generated art is used for content that is genuinely drawing —
 * icons, the title emblem, the backdrop and every entity.
 */

/** Animation keys, so gameplay code never types a string literal. */
export const ANIM = {

} as const;
