// GENERATED by scripts/gen-art-registry.mjs — do not edit by hand; edit art/manifest.json + regenerate.
/**
 * Generated-art registry: the only place that knows asset paths and frame
 * geometry. Every sheet under `public/assets/generated/` was produced by the
 * `game-art` skill (native generate_image + sprite-forge export) against
 * `art/style.json`, so the whole set shares one style contract.
 *
 * Frame geometry and per-action scale come from each asset's
 * `sprite-metadata.json` and `art/manifest.json` — never hand-guessed. To
 * change a row here, edit the manifest (or re-export the asset) and re-run
 * `node scripts/gen-art-registry.mjs`.
 *
 * Pure data, no Phaser import.
 */

export interface SpriteAsset {
  /** Phaser texture key; also the animation key when `frames > 1`. */
  key: string;
  /** Path under `public/`. */
  path: string;
  frameWidth: number;
  frameHeight: number;
  frames: number;
  /** ms per frame; ignored when `frames === 1`. */
  duration: number;
  loop: boolean;
  /**
   * Display-size compensation. Generated actions do not fill their cell to the
   * same height, so switching animation would visibly resize the character.
   * The entity multiplies its tuned size by this factor, which is
   * `baseActionHeight / thisActionHeight` (see `baseAction` in
   * art/manifest.json). Default 1.
   */
  scale?: number;
  /**
   * Which way the unflipped art faces. Some art reads as moving LEFT (cloak
   * trails right), so flipping on `velocity.x < 0` would face it backwards.
   * Default true.
   */
  facesRight?: boolean;
}

/** Animated sheets: loaded as spritesheets, one animation created per entry. */
export const SPRITES: readonly SpriteAsset[] = [
  // Hero
  { key: 'hero-idle', path: 'assets/generated/hero/hero-idle/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 140, loop: true, facesRight: false },
  { key: 'hero-run', path: 'assets/generated/hero/hero-run/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 8, duration: 110, loop: true, scale: 1.17, facesRight: false },
  { key: 'hero-attack', path: 'assets/generated/hero/hero-attack/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false, scale: 1.059, facesRight: false },
  { key: 'hero-hurt', path: 'assets/generated/hero/hero-hurt/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 90, loop: false, scale: 1.038, facesRight: false },

  // Enemies Light
  { key: 'swarm-move', path: 'assets/generated/enemies-light/swarm-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: true },
  { key: 'runner-move', path: 'assets/generated/enemies-light/runner-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: true },
  { key: 'shooter-idle', path: 'assets/generated/enemies-light/shooter-idle/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 140, loop: true },
  { key: 'healer-idle', path: 'assets/generated/enemies-light/healer-idle/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 140, loop: true },

  // Enemies Heavy
  { key: 'tank-move', path: 'assets/generated/enemies-heavy/tank-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 130, loop: true },
  { key: 'splitter-move', path: 'assets/generated/enemies-heavy/splitter-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 120, loop: true },
  { key: 'elite-move', path: 'assets/generated/enemies-heavy/elite-move/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 110, loop: true },
  { key: 'boss-idle', path: 'assets/generated/enemies-heavy/boss-idle/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 150, loop: true },

  // Pickups Fx
  { key: 'xp-orb', path: 'assets/generated/pickups-fx/xp-orb/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 90, loop: true },
  { key: 'coin', path: 'assets/generated/pickups-fx/coin/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 90, loop: true },
  { key: 'hit-spark', path: 'assets/generated/pickups-fx/hit-spark/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 60, loop: false },
  { key: 'levelup-burst', path: 'assets/generated/pickups-fx/levelup-burst/sprite-sheet.png', frameWidth: 128, frameHeight: 128, frames: 4, duration: 90, loop: false },

  // Chrome (panels, buttons, bar housings) is drawn with src/ui/primitives.ts, not generated: geometry must fit any size and follow PALETTE. Only glyphs and emblems are generated here. Loaded as spritesheets so a frame index can be selected; no animation is created.
  { key: 'icons', path: 'assets/generated/ui/icons/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },
  { key: 'icons-b', path: 'assets/generated/ui/icons-b/sprite-sheet.png', frameWidth: 256, frameHeight: 256, frames: 4, duration: 0, loop: false },
] as const;

/** Single-image textures: no animation, no frame slicing. */
export const IMAGES: readonly SpriteAsset[] = [
  // Pickups Fx
  { key: 'bullet', path: 'assets/generated/pickups-fx/bullet/sprite.png', frameWidth: 128, frameHeight: 128, frames: 1, duration: 0, loop: false },

  // Bounded field surface. `floor` is a seamless 512 tile drawn through a TileSprite; decals are flat, non-colliding and dimmed in data/props.ts.
  { key: 'arena-floor', path: 'assets/generated/arena/floor/sprite.png', frameWidth: 512, frameHeight: 512, frames: 1, duration: 0, loop: false },
  { key: 'arena-cracks', path: 'assets/generated/arena/decal-cracks/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'arena-plate', path: 'assets/generated/arena/decal-plate/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },

  // Impassable arena obstacles. Static 1x1 props, hd-fx, cellSize 256; collision is a circle sized by data/props.ts bodyScale.
  { key: 'prop-rock', path: 'assets/generated/props/rock/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'prop-crystal', path: 'assets/generated/props/crystal/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'prop-pillar', path: 'assets/generated/props/pillar/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },
  { key: 'prop-stump', path: 'assets/generated/props/stump/sprite.png', frameWidth: 256, frameHeight: 256, frames: 1, duration: 0, loop: false },

  // Full-bleed backdrop plus the title emblem. `arena` ships at its raw provider aspect (2:3 portrait, close to the 9:16 frame); ui/background.ts uniform-cover-fits it so nothing stretches. Additional parallax layers for authored spaces (see skill://map-forge) are added here as bg-layer-0/1/2 with `textureAlias` set to that name.
  { key: 'bg-arena', path: 'assets/generated/bg/arena/sprite.png', frameWidth: 1664, frameHeight: 2496, frames: 1, duration: 0, loop: false },
  { key: 'logo', path: 'assets/generated/bg/logo/sprite.png', frameWidth: 1024, frameHeight: 1024, frames: 1, duration: 0, loop: false },
] as const;

const BY_KEY: Record<string, SpriteAsset> = {};
for (const asset of SPRITES) BY_KEY[asset.key] = asset;

/** Display-size factor for an animation key (1 when the asset needs none). */
export function artScale(key: string): number {
  return BY_KEY[key]?.scale ?? 1;
}

/** True when the unflipped art faces right. */
export function artFacesRight(key: string): boolean {
  return BY_KEY[key]?.facesRight ?? true;
}

/** Static texture keys, so gameplay code never types a string literal. */
export const TEXTURE = {
  bullet: 'bullet',
  backdrop: 'bg-arena',
  logo: 'logo',
} as const;

/** Frame index per icon inside the icon sheets. */
export const ICON = {
  heart: { key: 'icons', frame: 0 },
  star: { key: 'icons', frame: 1 },
  coin: { key: 'icons', frame: 2 },
  bolt: { key: 'icons', frame: 3 },
  shield: { key: 'icons-b', frame: 0 },
  skull: { key: 'icons-b', frame: 1 },
  clock: { key: 'icons-b', frame: 2 },
  levelUp: { key: 'icons-b', frame: 3 },
} as const;

/**
 * UI chrome (panels, buttons, bar housings) is NOT art: it is drawn with
 * primitives in `ui/primitives.ts` so it adapts to any size and re-skins with
 * `PALETTE`. Generated art is used for content that is genuinely drawing —
 * icons, the title emblem, the backdrop and every entity.
 */

/** Animation keys, so gameplay code never types a string literal. */
export const ANIM = {
  heroIdle: 'hero-idle',
  heroRun: 'hero-run',
  heroAttack: 'hero-attack',
  heroHurt: 'hero-hurt',
  xpOrb: 'xp-orb',
  coin: 'coin',
  hitSpark: 'hit-spark',
  levelUpBurst: 'levelup-burst',
} as const;
